### ISSUE TITLE
Compiled oordump.rpo

### ISSUE THREAD

**Issue by MishaIac** [tsudoko/deoptimizeobs#1]
Hello. Is it possible to get a compiled version of oordump.rpo? I tried to compile through MinGW, but it didn't work, and as I see there is no way to compile through MSVC.

**Comment by tsdko** [comment]
> but it didn't work

What exactly was the problem? It's possible there's an error in the Makefile or the instructions aren't clear enough.

> there is no way to compile through MSVC

There is a way but I was dumb enough not to write it down anywhere and now I don't remember the exact command line I'd used.

I can attach the built plugin later (assuming you still need it) but it would be nice to use this opportunity to improve the build instructions and/or fix issues with the build system if there are any.

**Comment by MishaIac** [comment]
I will be glad if you attach the compiled version. I think it didn’t work out for me through the Makefile due to the fact that I had never used it before, because I compiled all programs through Visual Studio. Tried to figure it out, but didn't work. Apparently I'm too used to Visual Studio...

**Comment by tsdko** [comment]
Added a binary release with a bunch of previously unreleased stuff that might or might not be useful. Let me know if you have any more problems.
